# coding: utf-8
require "jekyll"
require "html-proofer"
require 'open3'

# Test generated output has valid HTML and links.
task :test do
  image_name=ENV["IMAGE_NAME"]
  image_tag=ENV["IMAGE_TAG"]

  # Spin up docker
  cmd = %Q(
        docker run \
        --detach \
        --publish 4000:4000 \
        --tty \
        --volume "#{Dir.pwd}:/srv/jekyll" \
        "#{image_name}:#{image_tag}"
        )

  stdout, stderr, _ = Open3.capture3(cmd)

  unless stderr.empty?
    raise stderr
  end

  while !stdout.include? "Server running"
    puts stdout
    sleep 1
  end

  options = { :assume_extension => true }
  site_folder = File.join(Dir.pwd, "_site")
  HTMLProofer.check_directory(site_folder, options).run
end

task :default => ["test"]
