# coding: utf-8
require "jekyll"
require "html-proofer"
require "open3"

def verify(site_dir)
  options = {
    :assume_extension => true,
    :check_html => true,
    :enforce_https => true,
    :only_4xx => true,
    :check_unrendered_link => true,
    :check_opengraph => true,
  }
  HTMLProofer.check_directory(site_dir, options).run
end

# Test generated output has valid HTML and links.
task :test do
  image_name = ENV.fetch("IMAGE_NAME", "swedbankpay/jekyll-plantuml")
  image_tag = ENV.fetch("IMAGE_TAG", "latest")

  # Spin up docker
  cmd = %Q(
    docker run \
      --env JEKYLL_ENV=production \
      --tty \
      --volume "#{__dir__}:/srv/jekyll" \
      "#{image_name}:#{image_tag}"
      jekyll build
  )

  _, stderr, _ = Open3.capture3(cmd)

  unless stderr.empty?
    raise stderr
  end

  site_dir = File.join(__dir__, "_site")

  puts "Checking files in #{site_dir}:"
  puts Dir.entries(site_dir)

  verify(site_dir)
end

task :verify_output do
  verify
end

task :default => ["test"]
task :verify => ["verify_output"]
