version: 2
updates:
- package-ecosystem: docker
  directory: "/.docker"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/Oslo
  open-pull-requests-limit: 99
- package-ecosystem: bundler
  directory: "/.docker/entrypoint"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/Oslo
  open-pull-requests-limit: 99
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/Oslo
  open-pull-requests-limit: 99
- package-ecosystem: bundler
  directory: "/tests/full"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/Oslo
  open-pull-requests-limit: 99
