pull_request_rules:
  - name: Automatically approve dependency updates
    conditions:
      - label=dependencies
      - or:
          - author~=^dependabot(|-preview)\[bot\]$
          - author~=^payex-dev$
    actions:
      review:
        type: APPROVE

  - name: Automatic merge on approval
    conditions:
      - label=dependencies
      - or:
          - author~=^dependabot(|-preview)\[bot\]$
          - author~=^payex-dev$
    actions:
      merge:
        method: merge
        strict: smart

  - name: Thank contributor
    conditions:
      - merged
      - -author~=^.*\[bot\]$
    actions:
      comment:
        message: "Thank you @{{author}} for your contribution!"
