pull_request_rules:
  - name: Automatic approve on dependabot PR
    conditions:
      - and:
          label=dependencies
      - or:
          author~=^dependabot(|-preview)\[bot\]$
          author~=^github-actions\[bot\]$
    actions:
      review:
        type: APPROVE

  - name: Automatic merge on approval
    conditions:
      - and:
          label=dependencies
      - or:
          author~=^dependabot(|-preview)\[bot\]$
          author~=^github-actions\[bot\]$
    actions:
      merge:
        method: merge
        strict: smart

  - name: Thank contributor
    conditions:
      - merged
    actions:
      comment:
        message: "Thank you @{{author}} for your contribution!"
