pull_request_rules:
  - name: Automatic approve on dependabot PR
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
    actions:
      review:
        type: APPROVE

  - name: Automatic merge on approval
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - '#commits-behind=0' # Only merge up to date pull requests
      - check-success=docker-verify
      - check-success=test-deploy
      - check-success=test-serve
      - check-success=test-serve-no-gemfile
      - check-success=test-build
      - check-success=test-build-gemspec
      - check-success=verify-output
      - check-success=hadolint
      - check-success=verify-bash
      - check-success=rspec
      - check-success=license/cla
    actions:
      merge:

  - name: Thank contributor
    conditions:
      - merged
      - -author~=^.*\[bot\]$
    actions:
      comment:
        message: "Thank you for your contribution, @{{author}}! :pray:"
