pull_request_rules:
  - name: Automatically approve dependency updates
    conditions:
      - or:
        - and:
            author~=^dependabot(|-preview)\[bot\]$
            label=dependencies
        - and:
            author~=^github-actions\[bot\]$
            label=dependencies
    actions:
      review:
        type: APPROVE

  - name: Automatic merge on approval
    conditions:
      - or:
        - and:
            author~=^dependabot(|-preview)\[bot\]$
            label=dependencies
        - and:
            author~=^github-actions\[bot\]$
            label=dependencies
    actions:
      merge:
        method: merge
        strict: smart

  - name: Thank contributor
    conditions:
      - merged
      - -author~=^.*\[bot\]$
    actions:
      comment:
        message: "Thank you @{{author}} for your contribution!"
