# frozen_string_literal: true

source 'https://rubygems.org'

gem 'html-proofer'
gem 'html-proofer-unrendered-markdown'
gem 'jekyll', '~> 4.2', group: :jekyll_plugins
gem 'open3', '~> 0.1.1'
gem 'rake'

gem 'jekyll-material-icon-tag', '~> 1.1'
gem 'jemoji', '~> 0.12.0'
gem 'kramdown-plantuml', '>= 1.1.12'
gem 'swedbank-pay-design-guide-jekyll-theme', '>= 1.12.4'
