#!/bin/bash

# This config comes from Nokogiri error output as a suggestion
bundle config build.nokogiri --use-system-libraries

bundle check || bundle install

echo "Running: $@"

if [[ "$@" == "ci" ]]; then
  exec /usr/jekyll/bin/ci-build-publish
else
  exec $@
fi
