#!/bin/bash

[ "${DEBUG:-false}" = "true" ] && set -x

# This config comes from Nokogiri error output as a suggestion
bundle config build.nokogiri --use-system-libraries

bundle check || bundle install

echo "Running: $*"

if [[ "$1" == "deploy" ]]; then
  bundle exec jekyll build JEKYLL_ENV=production --verbose
  exec /usr/jekyll/bin/deploy.sh
else
  exec "$@"
fi
