#!/bin/bash

if [[ "$DEBUG" == "true" ]]; then
    env                      # ...showing the environment
    cat "$GITHUB_EVENT_PATH" # ...and the GitHub webhook payload
    set -x                   # ...and script execution.
fi

# Any errors should cause an immediate exit and failure.
set -e

# Set publishing branch to 'gh-pages' by default.
if [[ -z $GH_PAGES_BRANCH ]]; then
    "$DEBUG" == "true" && echo "No GH_PAGES_BRANCH specified, defaulting to 'gh-pages'."
    GH_PAGES_BRANCH="gh-pages"
fi

# Set input variables
readonly gh_api_token="${GITHUB_TOKEN}"
readonly committer_name="${GITHUB_ACTOR}"
readonly commiter_email="${GITHUB_ACTOR_EMAIL}"
readonly publishing_branch="${GH_PAGES_BRANCH}"
readonly jekyll_env="${JEKYLL_ENV}"
readonly github_repository="${GITHUB_REPO}"

# Initialize Git if there's no .git folder
if [[ ! -d ".git" ]]; then
    "$DEBUG" == "true" && echo "Git not initialized. Initializing."
    git init
    git add --all .
    "$DEBUG" == "true" && echo "Configuring Git user and remote."
    git config user.email "${commiter_email}" || exit $?
    git config user.name "${committer_name}" || exit $?
    git remote add origin "https://x-access-token:${gh_api_token}@github.com/${github_repository}.git" || exit $?
    git commit --message 'Initial commit'
else
    "$DEBUG" == "true" && echo "Configuring Git user and remote."
    git config user.email "${commiter_email}" || exit $?
    git config user.name "${committer_name}" || exit $?
    git remote set-url origin "https://x-access-token:${gh_api_token}@github.com/${github_repository}.git" || exit $?
fi

branch_existed=false
# If $publishing_branch doesn't exist, create and track it.
if git show-ref --verify --quiet refs/heads/${publishing_branch}; then
    branch_existed=true
    "$DEBUG" == "true" && echo "The branch '${publishing_branch}' was found successfully."
else
    branch_existed=true
    "$DEBUG" == "true" && echo "The branch '${publishing_branch}' was not found. Creating it."
    git branch ${publishing_branch}
fi

# Install bundler if it's not already available on $PATH.
if ! bundle_location="$(type -p bundle)" || [[ -z $bundle_location ]]; then
    "$DEBUG" == "true" && echo "Bundler not found. Installing bundler."
    gem install bundler --force
fi

bundle check || bundle install

# Build project
"$DEBUG" == "true" && echo "Jekyll build:${jekyll_env}"
bundle exec jekyll build JEKYLL_ENV=$jekyll_env --verbose || exit $?

branch_name="$(git rev-parse --abbrev-ref HEAD)"

if [[ "$branch_name" == "master" ]]; then
    cd _site
    git add --all .
    git commit --message "Autodeployed"
    "$DEBUG" == "true" && echo "Pushing to $publishing_branch"

    if [[ "$branch_existed" == "true" ]]; then
        git push --force origin "$publishing_branch" || exit $?
    else
        git push --set-upstream origin "$publishing_branch" || exit $?
    fi
else
    "$DEBUG" == "true" && echo "Branch '$branch_name' is not 'master', so nothing to do."
fi

"$DEBUG" == "true" && echo "Done!"
