#!/bin/bash

if [[ "$DEBUG" == "true" ]]; then
    env                      # ...showing the environment
    cat "$GITHUB_EVENT_PATH" # ...and the GitHub webhook payload
    set -x                   # ...and script execution.
elif [[ -z "$DEBUG" ]]; then
    DEBUG=false
fi

# Any errors should cause an immediate exit and failure.
set -e

if [[ -z "$GITHUB_TOKEN" ]]; then
    echo "Environment variable GITHUB_TOKEN missing. Please define it."
    exit 1
fi

if [[ -z "$GITHUB_ACTOR" ]]; then
    echo "Environment variable GITHUB_ACTOR missing. Please define it."
    exit 1
fi

if [[ -z "$GITHUB_ACTOR_EMAIL" ]]; then
    echo "Environment variable GITHUB_ACTOR_EMAIL missing. Please define it."
    exit 1
fi

if [[ -z "$GITHUB_ACTOR_EMAIL" ]]; then
    echo "Environment variable GITHUB_ACTOR_EMAIL missing. Please define it."
    exit 1
fi

if [[ -z "$GITHUB_REPO" ]]; then
    echo "Environment variable GITHUB_REPO missing. Please define it."
    exit 1
fi

if [[ -z "$JEKYLL_ENV" ]]; then
    "$DEBUG" == "true" && echo "No JEKYLL_ENV specified, defaulting to 'production'."
    JEKYLL_ENV="production"
fi

# Set publishing branch to 'gh-pages' by default.
if [[ -z "$GH_PAGES_BRANCH" ]]; then
    "$DEBUG" == "true" && echo "No GH_PAGES_BRANCH specified, defaulting to 'gh-pages'."
    GH_PAGES_BRANCH="gh-pages"
fi

# Initialize Git if there's no .git folder
if [[ ! -d ".git" ]]; then
    "$DEBUG" == "true" && echo "Git not initialized. Initializing."
    git init
    git add --all .
    "$DEBUG" == "true" && echo "Configuring Git user and remote."
    git config user.email "${GITHUB_ACTOR_EMAIL}" || exit $?
    git config user.name "${GITHUB_ACTOR}" || exit $?
    git remote add origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPO}.git" || exit $?
    git commit --message 'Initial commit'
else
    "$DEBUG" == "true" && echo "Configuring Git user and remote."
    git config user.email "${GITHUB_ACTOR_EMAIL}" || exit $?
    git config user.name "${GITHUB_ACTOR}" || exit $?
    git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPO}.git" || exit $?
fi

branch_existed=false
# If $GH_PAGES_BRANCH doesn't exist, create and track it.
if git show-ref --verify --quiet refs/heads/${GH_PAGES_BRANCH}; then
    branch_existed=true
    "$DEBUG" == "true" && echo "The branch '${GH_PAGES_BRANCH}' was found successfully."
else
    branch_existed=true
    "$DEBUG" == "true" && echo "The branch '${GH_PAGES_BRANCH}' was not found. Creating it."
    git branch ${GH_PAGES_BRANCH}
fi

# Install bundler if it's not already available on $PATH.
if ! bundle_location="$(type -p bundle)" || [[ -z $bundle_location ]]; then
    "$DEBUG" == "true" && echo "Bundler not found. Installing bundler."
    gem install bundler --force
fi

"$DEBUG" == "true" && echo "Bundle check or install."
bundle check || bundle install

# Build project
"$DEBUG" == "true" && echo "Jekyll build:${JEKYLL_ENV}"
bundle exec jekyll build JEKYLL_ENV=${JEKYLL_ENV} --verbose || exit $?

branch_name="$(git rev-parse --abbrev-ref HEAD)"

if [[ "$branch_name" == "master" ]]; then
    cd _site
    git add --all --force .

    # If we detect changes, commit them.
    # `git diff-index --quiet` returns 0 on no changes and 1 on changes
    if git diff-index --cached --quiet HEAD; then
        "$DEBUG" == "true" && echo "No changes detected. Nothing to do!"
    else
        "$DEBUG" == "true" && echo "Changes detected. Committing."
        git commit --message "Autodeployed"

        "$DEBUG" == "true" && echo "Pushing to $GH_PAGES_BRANCH"

        if [[ "$branch_existed" == "true" ]]; then
            git push --force origin "${GH_PAGES_BRANCH}" || exit $?
        else
            git push --set-upstream origin "${GH_PAGES_BRANCH}" || exit $?
        fi
    fi
else
    "$DEBUG" == "true" && echo "Branch '$branch_name' is not 'master', so nothing to do."
fi

"$DEBUG" == "true" && echo "Done!"
