# coding: utf-8
require 'jekyll'
require 'html-proofer'

# Test generated output has valid HTML and links.
task :test do
  options = { :assume_extension => true }
  HTMLProofer.check_directory("../../_site", options).run
end

task :default => ["test"]