AllCops:
  NewCops: enable
Metrics/BlockLength:
  Exclude:
    - "Rakefile"
    - "spec/**/*.rb"
Metrics/MethodLength:
  Exclude:
    - "Rakefile"
    - "spec/**/*.rb"
Layout:
  LineLength: 80
  IndentationStyle:
    IndentationWidth: 2
