# frozen_string_literal: true

source 'https://rubygems.org'

group :jekyll_plugins do
  gem 'jekyll', '~> 4.1.1'
  gem 'jekyll-assets'
  gem 'jekyll-github-metadata'
  gem 'jekyll-material-icon-tag'
  gem 'jemoji'
  gem 'kramdown-plantuml'
  gem 'rouge'
end

gem 'concurrent-ruby'
gem 'docopt'
# Neccessary to prevent Jekyll errors. See https://github.com/github/personal-website/issues/166
gem 'faraday', '~> 1.0.1'
gem 'html-proofer', git: 'https://github.com/NullableInt/html-proofer', branch: 'feature/cache_local_links'
gem 'html-proofer-unrendered-markdown'
gem 'rake', '~> 13.0'

group :development, :test do
  gem 'diffy'
  gem 'rspec'
  gem 'rubocop', require: false
end

gem 'codecov', require: false, group: :test
