# frozen_string_literal: true

source 'https://rubygems.org'

gem 'concurrent-ruby', '~> 1.0'
gem 'docopt', '>= 0.6'
gem 'faraday', '> 1.0'
gem 'jekyll', '~> 4'
gem 'jekyll-material-icon-tag', '~> 1.0'
gem 'jemoji', '>= 0.12'
gem 'kramdown-plantuml', '>= 1.1.12'
gem 'rouge', '~> 4'

group :development, :test do
  gem 'codecov', '>= 0.6'
  gem 'diffy', '~> 3'
  gem 'html-proofer', '~> 5'
  gem 'html-proofer-unrendered-markdown', '>= 0.1'
  gem 'its', '>= 0.2'
  gem 'rake', '~> 13'
  gem 'rspec', '~> 3'
  gem 'rubocop', '~> 1'
  gem 'rubocop-rake', '>= 0.6'
  gem 'rubocop-rspec', '~> 2'
end
