require "rake"
require "rspec/core/rake_task"
require "rubocop/rake_task"

RSpec::Core::RakeTask.new(:spec) do |t|
  t.pattern = Dir.glob("spec/*_spec.rb")
  t.rspec_opts = "--format documentation"
end

task :rubocop do
  RuboCop::RakeTask.new
end

task :default => :spec
