name: apt update

on:
  schedule:
  - cron: "30 2 * * *"
  workflow_dispatch:

jobs:
  apt-update:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    # This container image needs to match the base image used in the Dockerfile
    container: debian:bullseye-slim

    steps:
    - run: apt-get update
    - run: apt-get install -y git jq

    - uses: actions/checkout@v3

    - name: update apt.json
      run: .github/scripts/apt_update.sh --file .docker/apt.json

    - uses: actions/upload-artifact@v2
      with:
        name: apt.json
        path: .docker/apt.json

    - uses: peter-evans/create-pull-request@v4
      with:
        commit-message: |
          Update apt.json

          Bump APT packages to their latest versions in `apt.json`.
        branch: feature/update-apt-json
        title: Update APT packages
        body: Bump APT packages to their latest versions in `apt.json`.
        delete-branch: true
        labels: dependencies, apt
        committer: PayEx <dev@payex.com>
        author: PayEx <dev@payex.com>
        token: ${{ secrets.APT_UPDATE_TOKEN }}
