name: apt update

on: [push]

jobs:
  apt-update:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container: debian:buster-slim

    steps:
    - uses: actions/checkout@v2.3.4

    - run: sudo apt-get update

    - name: update apt.json
      working-directory: .docker
      run: ${{ github.workspace }}/.github/scripts/apt_update.sh --verbose

    - uses: actions/upload-artifact@v2
      with:
        name: apt.json
        path: /tmp/apt.json

    - uses: peter-evans/create-pull-request@v3
      with:
        commit-message: |
          Update apt.json

          Bump APT packages to their latest versions in `apt.json`.
        branch: feature/update-apt-json
        title: Update APT packages
        body: Bump APT packages to their latest versions in `apt.json`.
        delete-branch: true
        labels: dependencies, apt
        committer: PayEx <dev@payex.com>
        author: PayEx <dev@payex.com>
        token: ${{ secrets.APT_UPDATE_TOKEN}}
