name: apt update

on: [push]

jobs:
  apt-update:
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Update dependencies
      working-directory: .docker
      run: |
        sudo apt-get update
        sh ${{ github.workspace }}/.github/scripts/apt_update.sh

    - name: Create PR
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: "Update apt.json"
        branch: features/update-apt-json
        title: Update apt packages
        body: Updated apt.json
        delete-branch: true
        labels: dependencies, apt
