name: apt update
on:
  schedule:
  - cron: "30 2 * * *"
  workflow_dispatch:

jobs:
  apt-update:
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2.3.4

    - name: apt-get update
      working-directory: .docker
      run: |
        sudo apt-get update
        sh ${{ github.workspace }}/.github/scripts/apt_update.sh

    - uses: peter-evans/create-pull-request@v3
      with:
        commit-message: |
          Update apt.json

          Bump APT packages to their latest versions in `apt.json`.
        branch: feature/update-apt-json
        title: Update APT packages
        body: Bump APT packages to their latest versions in `apt.json`.
        delete-branch: true
        labels: dependencies, apt
        committer: PayEx <dev@payex.com>
        author: PayEx <dev@payex.com>
        token: ${{ secrets.APT_UPDATE_TOKEN}}
