name: apt update

on: [push]

jobs:
  variables:
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ steps.variables.outputs.ref }}
      sha: ${{ steps.variables.outputs.sha }}
      sha8: ${{ steps.variables.outputs.sha8 }}
      date: ${{ steps.variables.outputs.date }}
      version: ${{ steps.variables.outputs.version }}
      build_branch: ${{ steps.variables.outputs.build_branch }}
      deploy_branch: ${{ steps.variables.outputs.deploy_branch }}
      ghpr_docker_image_fqn: ${{ steps.variables.outputs.ghpr_docker_image_fqn }}
      ghpr_docker_image_tag: ${{ steps.variables.outputs.docker_image_tag }}

    steps:
      - uses: actions/checkout@v2

      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.10
        with:
          versionSpec: "5.x.x"

      - name: GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.10

      - name: Generate variables
        id: variables
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: ./.github/scripts/variables.sh ${{ steps.gitversion.outputs.fullSemVer }}

  docker-build:
    needs: variables
    runs-on: ubuntu-latest
    steps:
    - name: Build Docker Image
      uses: whoan/docker-build-with-cache-action@v5.11.1
      with:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        image_name: jekyll-plantuml
        image_tag: ${{ needs.variables.outputs.sha8 }}
        dockerfile: .docker/Dockerfile
        push_image_and_stages: true
        pull_image_and_stages: true
        build_extra_args: --build-arg SHA=${{ needs.variables.outputs.sha }} --build-arg TAG=${{ needs.variables.outputs.sha8 }} --build-arg DATE=${{ needs.variables.outputs.date }} --build-arg VERSION=${{ needs.variables.outputs.version }}

  apt-update:
    needs: [variables, docker-build]
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: docker.pkg.github.com/swedbankpay/jekyll-plantuml:${{ needs.variables.outputs.sha8 }}
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v2.3.4

    - name: apt-get update
      run: /bin/apt_update.sh

    - uses: actions/upload-artifact@v2
      with:
        name: apt.json
        path: .docker/apt.json

    - uses: peter-evans/create-pull-request@v3
      with:
        commit-message: |
          Update apt.json

          Bump APT packages to their latest versions in `apt.json`.
        branch: feature/update-apt-json
        title: Update APT packages
        body: Bump APT packages to their latest versions in `apt.json`.
        delete-branch: true
        labels: dependencies, apt
        committer: PayEx <dev@payex.com>
        author: PayEx <dev@payex.com>
        token: ${{ secrets.APT_UPDATE_TOKEN}}
