name: Build and Publish

on:
  push:
    branches: [ master ]
    tags: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Generate version number
      id: version
      run: |
        ref="${{ github.ref }}"
        if [[ "$ref" == refs/tags/* ]]; then
          version="${ref#refs/tags/}"
        else
          version="latest"
        fi
        echo "Version: ${version}"
        echo "::set-output name=version::${version}"

    - name: Publish unstable Docker image to GitHub Package Registry
      if: startsWith(github.ref, 'refs/tags/') != true
      uses: whoan/docker-build-with-cache-action@v5.3.0
      with:
        username: swedbankpay
        password: "${{ secrets.GITHUB_TOKEN }}"  # you don't need to manually set this secret. GitHub does it on your behalf
        registry: docker.pkg.github.com
        image_name: swedbankpay/jekyll-plantuml
        image_tag: ${{ steps.version.outputs.version }}
        dockerfile: ".docker/Dockerfile"
        push_image_and_stages: docker run --tty --volume ${{ github.workspace }}/test/jekyll-plantuml:/srv/jekyll swedbankpay/jekyll-plantuml:${{ steps.version.outputs.version }} 'jekyll build'
        pull_image_and_stages: false

    - name: Publish stable Docker image to Docker Hub
      if: startsWith(github.ref, 'refs/tags/')
      uses: whoan/docker-build-with-cache-action@v5.3.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: "${{ secrets.DOCKERHUB_PASSWORD}}"  # you don't need to manually set this secret. GitHub does it on your behalf
        image_name: swedbankpay/jekyll-plantuml
        image_tag: ${{ steps.version.outputs.version }}
        dockerfile: ".docker/Dockerfile"
        push_image_and_stages: docker run --tty --volume ${{ github.workspace }}/test/jekyll-plantuml:/srv/jekyll swedbankpay/jekyll-plantuml:${{ steps.version.outputs.version }} "jekyll build"
        pull_image_and_stages: false