name: Docker CI build and run

on:
  push:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build docker image
      run: |
        docker build . --file .\.docker\Dockerfile --tag swedbankpay/jekyll-plantuml:ci

    - name: Run docker image
      run: |
        docker run swedbankpay/jekyll-plantuml:ci "jekyll build"