name: Docker CI build and run

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build docker image
      run: |
        docker build . --file ./.docker/Dockerfile --tag swedbankpay/jekyll-plantuml:ci

    - name: Run docker image
      run: |
        docker run --tty --volume ${{ github.workspace }}/test/jekyll-plantuml:/srv/jekyll swedbankpay/jekyll-plantuml:ci "ls -la"