name: Docker Image CI

on:
  push:
    branches: [ master ]
    tags: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Generate version number
      id: version
      run: |
        ref="${{ github.ref }}"
        if [[ "$ref" == refs/tags/* ]]; then
          version="${ref#refs/tags/}"
        else
          version="latest"
        fi
        echo "Version: ${version}"
        echo "::set-output name=version::${version}"

    - name: Build the Docker image
      run: |
        docker build \
          .docker \
          --file .docker/Dockerfile \
          --tag swedbankpay/jekyll-plantuml:${{ steps.version.outputs.version }} \
          --tag docker.pkg.github.com/swedbankpay/jekyll-plantuml-docker/jekyll-plantuml:${{ steps.version.outputs.version }}

    - name: Run Docker image
      working-directory: test/jekyll-plantuml
      run: |
        echo "Volume folder: ${{ github.workspace }}/test/jekyll-plantuml"
        docker run \
          --tty \
          --volume ${{ github.workspace }}/test/jekyll-plantuml:/srv/jekyll \
          swedbankpay/jekyll-plantuml:${{ steps.version.outputs.version }}

    - name: Publish unstable Docker image to GitHub Package Registry
      if: startsWith(github.ref, 'refs/tags/') != true
      run: |
        docker login -u SwedbankPay -p ${{ secrets.GITHUB_TOKEN}} docker.pkg.github.com
        docker push docker.pkg.github.com/swedbankpay/jekyll-plantuml-docker/jekyll-plantuml:${{ steps.version.outputs.version }}

    - name: Publish stable Docker image to Docker Hub
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        docker login -u  ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD}} 
        docker push swedbankpay/jekyll-plantuml:${{ steps.version.outputs.version }}