name: Build and Publish Docker Image

on:
  push:
    branches: [ master ]
    tags: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-publish-docker-image:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.variables.outputs.version }}
      output2: ${{ steps.variables.outputs.version }}

    steps:
    - uses: actions/checkout@v2

    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.3
      with:
        versionSpec: '5.x.x'

    - name: GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.3

    - name: Generate variables
      id: variables
      run: ./.github/workflows/variables.sh ${{ github.sha }} ${{ github.ref }} ${{ steps.gitversion.outputs.fullSemVer }}

    - name: Publish unstable Docker image to GitHub Package Registry
      if: startsWith(github.ref, 'refs/tags/') != true
      uses: whoan/docker-build-with-cache-action@v5.3.3
      with:
        username: ${{ github.repository_owner }}
        password: "${{ secrets.GITHUB_TOKEN }}"
        registry: docker.pkg.github.com
        image_name: jekyll-plantuml
        image_tag: ${{ steps.variables.outputs.sha8 }}
        dockerfile: .docker/Dockerfile
        push_image_and_stages: ./.github/workflows/docker_run_test.sh build
        pull_image_and_stages: false
        build_extra_args: --build-arg SHA="$SHA" --build-arg DATE="$DATE" --build-arg VERSION="$VERSION"
      env:
        SHA: ${{ steps.variables.outputs.sha }}
        TAG: ${{ steps.variables.outputs.version }}
        DATE: ${{ steps.variables.outputs.date }}
        VERSION: ${{ steps.variables.outputs.version }}
        JEKYLL_DIR: ${{ github.workspace }}/.docker/jekyll-plantuml
        IMAGE_NAME: docker.pkg.github.com/swedbankpay/jekyll-plantuml-docker/jekyll-plantuml
        DEBUG: true

    - name: Publish stable Docker image to Docker Hub
      if: startsWith(github.ref, 'refs/tags/')
      uses: whoan/docker-build-with-cache-action@v5.3.3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: "${{ secrets.DOCKERHUB_PASSWORD }}"
        image_name: swedbankpay/jekyll-plantuml
        image_tag: ${{ steps.variables.outputs.version }}
        dockerfile: .docker/Dockerfile
        push_image_and_stages: ./.github/workflows/docker_run_test.sh build
        pull_image_and_stages: false
        build_extra_args: --build-arg SHA="$SHA" --build-arg DATE="$DATE" --build-arg VERSION="$VERSION"
      env:
        SHA: ${{ steps.variables.outputs.sha }}
        TAG: ${{ steps.variables.outputs.version }}
        DATE: ${{ steps.variables.outputs.date }}
        VERSION: ${{ steps.variables.outputs.version }}
        JEKYLL_DIR: ${{ github.workspace }}/.docker/jekyll-plantuml

  verify-image:
    runs-on: ubuntu-latest
    needs: build-and-publish-docker-image

    steps:
    - name: Download and run image from GitHub Package Registry
      if: startsWith(github.ref, 'refs/tags') != true
      env:
        TAG: ${{ needs.build-and-publish-docker-image.variables.outputs.version }}
        JEKYLL_DIR: ${{ github.workspace }}/.docker/jekyll-plantuml
        IMAGE_NAME: docker.pkg.github.com/swedbankpay/jekyll-plantuml-docker/jekyll-plantuml
      run: |
        docker login https://docker.pkg.github.com -u ${{ github.repository_owner }} -p "${{ secrets.GITHUB_TOKEN }}"
        docker pull ${IMAGE_NAME}:${TAG}
        ./.github/workflows/docker_run_test.sh build

    - name: Download and run image from Docker Hub
      if: startsWith(github.ref, 'refs/tags')
      env:
        TAG: ${{ needs.build-and-publish-docker-image.variables.outputs.version }}
        JEKYLL_DIR: ${{ github.workspace }}/.docker/jekyll-plantuml
      run: |
        docker pull swedbankpay/jekyll-plantuml:${TAG}
        ./.github/workflows/docker_run_test.sh build
