name: Docker Image CI

on:
  push:
    branches: [ master ]
    tags: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Generate version number
      id: version
      run: |
        ref="${{ github.ref }}"
        if [[ "$ref" == "refs/tags/*" ]]; then
          version="${ref#refs/tags/}"
        else
          version="latest"
        fi
        echo "Version: ${version}"
        echo "::set-output name=version::${version}"

    - name: Build the Docker image
      run: |
        docker build \
          .docker \
          --file .docker/Dockerfile \
          --tag jekyll-plantuml:${{ steps.version.outputs.version }}

    - name: Run Docker image
      working-directory: test/jekyll-plantuml
      run: |
        echo "Volume folder: $(pwd)/test/jekyll-plantuml"
        docker run \
          --tty \
          --volume $(pwd)/test/jekyll-plantuml:/srv/jekyll \
          jekyll-plantuml:${{ steps.version.outputs.version }}

    - name: Docker Publish
      if: startsWith(github.ref, 'refs/tags/')
      uses: manusa/actions-publish-docker@v1.0.1
      with:
        # Name of the Docker image
        name: SwedbankPay/jekyll-plantuml
        # Tag for the Docker image
        tag: ${{ steps.version.outputs.version }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        include pull requests: false
