name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.2
      with:
        versionSpec: '5.2.x'

    - name: Execute GitVersion
      id: gitversion # step id used as reference for output values
      uses: gittools/actions/gitversion/execute@v0.9.2

    - name: Generate version number
      id: version
      run: |
        semver="${{ steps.gitversion.outputs.fullSemVer }}"
        version="${semver/+/.alpha-}" # Replace `+` with `.alpha-`
        echo "Version: ${version}"
        echo "::set-output name=version::${version}"

    - name: Build the Docker image
      run: |
        docker build \
          .docker \
          --file .docker/Dockerfile \
          --tag jekyll-plantuml:${{ steps.version.outputs.version }}

    - name: Run Docker image
      working-directory: test/jekyll-plantuml
      run: |
        docker run \
          --tty \
          --volume $(pwd)/test/jekyll-plantuml:/srv/jekyll \
          jekyll-plantuml:${{ steps.version.outputs.version }}

    - name: Docker Publish
      if: startsWith(github.ref, 'refs/tags/')
      uses: manusa/actions-publish-docker@v1.0.1
      with:
        # Name of the Docker image
        name: SwedbankPay/jekyll-plantuml
        # Tag for the Docker image
        tag: ${{ steps.version.outputs.version }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        include pull requests: false
