name: Docker Image CI

on:
  push:
    branches: [ master ]
    tags: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Generate version number
      id: version
      run: |
        ref="${{ github.ref }}"
        if [[ "$ref" == refs/tags/* ]]; then
          version="${ref#refs/tags/}"
        else
          version="latest"
        fi
        echo "Version: ${version}"
        echo "::set-output name=version::${version}"

    - name: Build the Docker image
      run: |
        docker build \
          .docker \
          --file .docker/Dockerfile \
          --tag jekyll-plantuml:${{ steps.version.outputs.version }}

    - name: Run Docker image
      working-directory: test/jekyll-plantuml
      run: |
        echo "Volume folder: ${{ github.workspace }}/test/jekyll-plantuml"
        docker run \
          --tty \
          --volume ${{ github.workspace }}/test/jekyll-plantuml:/srv/jekyll \
          jekyll-plantuml:${{ steps.version.outputs.version }}

    - name: Publish unstable Docker image to GitHub Package Registry
      if: startsWith(github.ref, 'refs/tags/') != true
      uses: docker/build-push-action@v1
      with:
        username: SwedbankPay
        password: ${{ secrets.GITHUB_TOKEN }}
        repository: docker.pkg.github.com
        tags: ${{ steps.version.outputs.version }}
        dockerfile: ".docker"

    - name: Publish stable Docker image to Docker Hub
      if: startsWith(github.ref, 'refs/tags/')
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        tags: ${{ steps.version.outputs.version }}
        dockerfile: ".docker"
