name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag jekyll-plantuml:$(date +%s)
    - name: Docker Publish
      uses: manusa/actions-publish-docker@v1.0.1
      with:
        # Name of the Docker image
        name: SwedbankPay/jekyll-plantuml
        # Tag for the Docker image
        tag script: |
          return context.ref
            .replace('refs/heads/
            .replace('refs/tags/'
            .replace('refs/pull/'
            .replace(/\//g, '_')
            .replace(/#/g, '');
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        # Registry URL
        # Don't skip pull requests
        include pull requests: false
