name: Build and Publish Docker Image

on:
  push:
    branches: [ master ]
    tags: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-publish-docker-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Generate version number
      id: version
      run: |
        ref="${{ github.ref }}"
        if [[ "$ref" == refs/tags/* ]]; then
          version="${ref#refs/tags/}"
        else
          version="${{ github.sha }}"
        fi
        echo "Version: ${version}"
        echo "::set-output name=version::${version}"

    - name: Publish unstable Docker image to GitHub Package Registry
      if: startsWith(github.ref, 'refs/tags/') != true
      uses: whoan/docker-build-with-cache-action@v5.3.3
      with:
        username: ${{ github.repository_owner }}
        password: "${{ secrets.GITHUB_TOKEN }}"
        registry: docker.pkg.github.com
        image_name: jekyll-plantuml
        image_tag: ${{ steps.version.outputs.version }}
        dockerfile: ".docker/Dockerfile"
        push_image_and_stages: docker run --tty --volume ${{ github.workspace }}/.docker/jekyll-plantuml:/srv/jekyll docker.pkg.github.com/swedbankpay/jekyll-plantuml-docker/jekyll-plantuml:${{ steps.version.outputs.version }} jekyll build
        pull_image_and_stages: false
      env:
        DEBUG: true

    - name: Publish stable Docker image to Docker Hub
      if: startsWith(github.ref, 'refs/tags/')
      uses: whoan/docker-build-with-cache-action@v5.3.3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: "${{ secrets.DOCKERHUB_PASSWORD }}"
        image_name: swedbankpay/jekyll-plantuml
        image_tag: ${{ steps.version.outputs.version }}
        dockerfile: ".docker/Dockerfile"
        push_image_and_stages: docker run --tty --volume ${{ github.workspace }}/.docker/jekyll-plantuml:/srv/jekyll swedbankpay/jekyll-plantuml:${{ steps.version.outputs.version }} jekyll build
        pull_image_and_stages: false

  verify-image:
    runs-on: ubuntu-latest
    needs: build-and-publish-docker-image

    steps:
    - name: Download and run image from GitHub Package Registry
      if: startsWith(github.ref, 'refs/tags') != true
      run: |
        docker login https://docker.pkg.github.com -u ${{ github.repository_owner }} -p "${{ secrets.GITHUB_TOKEN }}"
        docker pull docker.pkg.github.com/swedbankpay/jekyll-plantuml-docker/jekyll-plantuml:${{ steps.version.outputs.version }}
        docker run \
        --tty \
        --volume ${{ github.workspace }}/test/jekyll-plantuml:/srv/jekyll \
        docker.pkg.github.com/swedbankpay/jekyll-plantuml-docker/jekyll-plantuml:${{ steps.version.outputs.version }} \
        jekyll build

    - name: Download and run image from Docker Hub
      if: startsWith(github.ref, 'refs/tags')
      run: |
        docker pull swedbankpay/jekyll-plantuml:${{ steps.version.outputs.version }}
        docker run \
        --tty \
        --volume ${{ github.workspace }}/test/jekyll-plantuml:/srv/jekyll \
        swedbankpay/jekyll-plantuml:${{ steps.version.outputs.version }} \
        jekyll build
