name: Test gh-pages-publish

on: [push, pull_request]

jobs:
  build:
    name: Docker build site and publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build docker image
      run: |
        docker build . --file ./.docker/Dockerfile --tag swedbankpay/jekyll-plantuml:ci

    - name: Init git in test folder
      run: |
        git init ./test/jekyll-plantuml

    - name: Test gh-pages-publish
      env:
        secret_gh_pages_api_token: ${{ secrets.GITHUB_TOKEN }}
        git_committer_email: dev@payex.com
        git_committer_name: payex-dev
        DEBUG: "true"
        GITHUB_ACTOR: payex-dev
        JEKYLL_GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
        JEKYLL_ENV: production
      run: |
        docker run  \
        --tty --volume ${{ github.workspace }}/test/jekyll-plantuml:/srv/jekyll \        
        --env GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
        --env JEKYLL_ENV="production" \
        --env GH_PAGES_BRANCH="gh-pages" \
        --env DEBUG=true \
        swedbankpay/jekyll-plantuml:ci \
        "gh-pages-publish"