name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow

    - name: ShellCheck
      uses: bewuethr/shellcheck-action@v2

    - name: Control Character Check
      run: ./.github/workflows/control_character_finder.sh

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.3
      with:
        versionSpec: '5.x.x'

    - name: GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.3

    - name: Generate variables
      id: variables
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: ./.github/workflows/variables.sh ${{ steps.gitversion.outputs.fullSemVer }}

    - name: Build Docker Image
      uses: whoan/docker-build-with-cache-action@v5.3.3
      with:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        image_name: jekyll-plantuml
        image_tag: ${{ steps.variables.outputs.sha8 }}
        dockerfile: .docker/Dockerfile
        push_image_and_stages: true
        pull_image_and_stages: true
        build_extra_args: --build-arg SHA="${{ steps.variables.outputs.sha }}" --build-arg DATE="${{ steps.variables.outputs.date }}" --build-arg VERSION="${{ steps.variables.outputs.version }}"

    - name: Run Docker Image (default command)
      env:
        IMAGE_TAG: ${{ steps.variables.outputs.sha8 }}
        IMAGE_NAME: docker.pkg.github.com/swedbankpay/jekyll-plantuml-docker/jekyll-plantuml
        JEKYLL_DIR: ${{ github.workspace }}/.docker/jekyll-plantuml
      run: ./.github/workflows/docker_run_test.sh serve

    - name: Run Docker Image (jekyll build, no Gemfile)
      env:
        IMAGE_TAG: ${{ steps.variables.outputs.sha8 }}
        IMAGE_NAME: docker.pkg.github.com/swedbankpay/jekyll-plantuml-docker/jekyll-plantuml
        JEKYLL_DIR: ${{ github.workspace }}
      run: ./.github/workflows/docker_run_test.sh build

    - name: Run Docker Image (jekyll build)
      env:
        IMAGE_TAG: ${{ steps.variables.outputs.sha8 }}
        IMAGE_NAME: docker.pkg.github.com/swedbankpay/jekyll-plantuml-docker/jekyll-plantuml
        JEKYLL_DIR: ${{ github.workspace }}/.docker/jekyll-plantuml
      run: ./.github/workflows/docker_run_test.sh build

    - name: Verify build output
      env:
        IMAGE_TAG: ${{ steps.variables.outputs.sha8 }}
        IMAGE_NAME: docker.pkg.github.com/swedbankpay/jekyll-plantuml-docker/jekyll-plantuml
        DEBUG: true
      run: ./.github/workflows/verify_build_output.sh

    - name: Test Deploy
      env:
        SHA8: ${{ steps.variables.outputs.sha8 }}
        WORK_DIR: ${{ github.workspace }}
        GIT_DEPLOY_DIR: _site
        GIT_DEPLOY_BRANCH: ${{ steps.variables.outputs.branch_name }}
        GIT_DEPLOY_REPO: https://${{ secrets.GH_PAGES_TOKEN }}@github.com/${{ github.repository }}.git
      run: |
        docker run \
          --volume ${WORK_DIR}/.docker/jekyll-plantuml:/srv/jekyll \
          --env GIT_DEPLOY_DIR="${GIT_DEPLOY_DIR}" \
          --env GIT_DEPLOY_BRANCH="${GIT_DEPLOY_BRANCH}" \
          --env GIT_DEPLOY_REPO="${GIT_DEPLOY_REPO}" \
          --env DEBUG="true" \
          swedbankpay/jekyll-plantuml:${SHA8} \
          deploy

    - name: Cleanup
      if: always()
      env:
        GIT_DEPLOY_BRANCH: ${{ steps.branch.outputs.name }}
      run: |
          git checkout --force ${{ github.sha }}
          if git show-ref --verify --quiet "refs/heads/${GIT_DEPLOY_BRANCH}"; then
              echo "Branch '${GIT_DEPLOY_BRANCH}' found. Deleting"
              git branch --delete --force "${GIT_DEPLOY_BRANCH}"
              git push --delete origin "${GIT_DEPLOY_BRANCH}"
          fi
