name: Test Deploy

on: [push, pull_request]

jobs:
  test-deploy:
    name: Test Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Shellcheck
      uses: bewuethr/shellcheck-action@v2

    - name: Control Character Check
      run: ./.github/workflows/control_character_finder.sh

    - name: Generate SHA
      id: sha
      env:
        GIT_SHA: ${{ github.sha }}
      run: |
        SHA8=$(echo ${GIT_SHA} | cut -c1-8)
        echo "SHA8: ${SHA8}"
        echo "::set-output name=sha8::${SHA8}"

    - name: Build Docker Image
      env:
        SHA8: ${{ steps.sha.outputs.sha8 }}
      run: |
        docker build \
          . \
          --file ./.docker/Dockerfile \
          --tag swedbankpay/jekyll-plantuml:${SHA8}

    - name: Run Docker Image (default command)
      env:
        SHA8: ${{ steps.sha.outputs.sha8 }}
      run: |
        { \
          docker run \
            --tty \
            --volume $(pwd)/test/jekyll-plantuml:/srv/jekyll \
            swedbankpay/jekyll-plantuml:${SHA8} \
            & echo $! > pid; \
        } | tee /dev/stderr | { \
          grep -m1 "Server running" \
          && kill -9 $(cat pid) \
          && rm pid; \
        }

    - name: Run Docker Image (jekyll build, no Gemfile)
      env:
        SHA8: ${{ steps.sha.outputs.sha8 }}
      run: |
        { \
          docker run \
            --tty \
            --volume ${{ github.workspace }}:/srv/jekyll \
            swedbankpay/jekyll-plantuml:${SHA8} \
            & echo $! > pid; \
        } | tee /dev/stderr | { \
          grep -m1 "Server running" \
          && kill -9 $(cat pid) \
          && rm pid; \
        }

    - name: Run Docker Image (jekyll build)
      env:
        SHA8: ${{ steps.sha.outputs.sha8 }}
      run: |
        docker run \
          --tty \
          --volume ${{ github.workspace }}/test/jekyll-plantuml:/srv/jekyll \
          swedbankpay/jekyll-plantuml:${SHA8} \
          jekyll build

    - name: Generate Branch Name
      id: branch
      run: |
        BRANCH_NAME="r${{ github.run_id }}-${{ github.run_number }}"
        echo "BRANCH_NAME: ${BRANCH_NAME}"
        echo "::set-output name=name::${BRANCH_NAME}"

    - name: Test Deploy
      env:
        SHA8: ${{ steps.sha.outputs.sha8 }}
        WORK_DIR: ${{ github.workspace }}
        GIT_DEPLOY_DIR: _site
        GIT_DEPLOY_BRANCH: ${{ steps.branch.outputs.name }}
        GIT_DEPLOY_REPO: https://${{ secrets.GH_PAGES_TOKEN }}@github.com/${{ github.repository }}.git
      run: |
        docker run \
          --volume ${WORK_DIR}/test/jekyll-plantuml:/srv/jekyll \
          --env GIT_DEPLOY_DIR="${GIT_DEPLOY_DIR}" \
          --env GIT_DEPLOY_BRANCH="${GIT_DEPLOY_BRANCH}" \
          --env GIT_DEPLOY_REPO="${GIT_DEPLOY_REPO}" \
          --env DEBUG="true" \
          swedbankpay/jekyll-plantuml:${SHA8} \
          deploy

    - name: Cleanup
      if: always()
      env:
        GIT_DEPLOY_BRANCH: ${{ steps.branch.outputs.name }}
      run: |
          git checkout --force ${{ github.sha }}
          if git show-ref --verify --quiet "refs/heads/${GIT_DEPLOY_BRANCH}"; then
              echo "Branch '${GIT_DEPLOY_BRANCH}' found. Deleting"
              git branch --delete --force "${GIT_DEPLOY_BRANCH}"
              git push --delete origin "${GIT_DEPLOY_BRANCH}"
          fi
