name: Verify Generated HTML

on: [push, pull_request]

jobs:
  verify-html:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker Image
      run: |
        docker build \
          . \
          --file ./.docker/Dockerfile \
          --tag swedbankpay/jekyll-plantuml:latest

    - name: Verify build output
      run: ./.github/workflows/verify_build_output.sh
