name: Verify Generated HTML

on: [push, pull_request]

jobs:
  verify-html:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Generate variables
      id: variables
      run: ./.github/workflows/variables.sh ${{ github.sha }} ${{ github.ref }} ${{ steps.gitversion.outputs.fullSemVer }}

    - name: Build Docker Image
      run: |
        docker build \
          . \
          --file ./.docker/Dockerfile \
          --build-arg SHA="${{ steps.variables.outputs.sha8 }}" \
          --build-arg DATE="${{ steps.variables.outputs.date }}" \
          --build-arg VERSION="${{ steps.variables.outputs.version }}" \
          --tag swedbankpay/jekyll-plantuml:latest

    - name: Verify build output
      run: ./.github/workflows/verify_build_output.sh
