name: Verify Generated HTML

on: [push, pull_request]

jobs:
  verify-html:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Build Docker Image
      env:
        DEBUG: true
      run: |
        docker build \
          . \
          --file ./.docker/Dockerfile \
          --tag swedbankpay/jekyll-plantuml:latest
      

    - name: Verify build output
      run: ./.github/workflows/verify_build_output.sh
